[package]
name = "advent_of_code_2015"
version = "0.1.0"
edition = "2024"

[lib]
name = "common"
path = "src/lib.rs"

[dev-dependencies]
test-case = "*"

[dependencies]
itertools = "0.14.0"
md5 = "0.8.0"
serde_json = "1.0.143"
